---
- hosts: all
  become: true
  vars:
    ansible_python_interpreter: /usr/bin/python3

  tasks:
    - name: Run "apt-get update"
      apt:
        update_cache: yes
        cache_valid_time: 86400
