---
- name: Configure Host
  hosts: all
  remote_user: deploy
  become: yes
  become_method: sudo
  tasks:
    - name: Set the timezone for the server to be UTC
      community.general.timezone:
        name: 'UTC'
    - name: Set up a unique hostname
      hostname: name={{'{{'}} inventory_hostname {{'}}'}}
    - name: Add the server's domain to the hosts file
      lineinfile: dest=/etc/hosts
                  regexp='.*{{'{{'}} item {{'}}'}}$'
                  line="{{'{{'}} hostvars[item].ansible_default_ipv4.address {{'}} {{'}} hostvars[item]['inventory_hostname'] {{'}} {{'}} hostvars[item]['inventory_hostname'] {{'}}'}}"
                  state=present
      when: hostvars[item].ansible_default_ipv4.address is defined
      with_items: "{{'{{'}} groups['all'] {{'}}'}}"
    - name: Update packages
      apt: update_cache=yes upgrade=dist